-- Create SOCIAL_MEDIA_DB:
        
CREATE OR REPLACE DATABASE SOCIAL_MEDIA_DB_AMS;


-- Create SCHEMAS:

CREATE OR REPLACE SCHEMA SOCIAL_MEDIA_DB_AMS.BRONZE;
CREATE OR REPLACE SCHEMA SOCIAL_MEDIA_DB_AMS.SILVER;
CREATE OR REPLACE SCHEMA SOCIAL_MEDIA_DB_AMS.GOLD;


-- Use:

USE WAREHOUSE LAB_WH_AMS;
USE DATABASE SOCIAL_MEDIA_DB_AMS;
USE SCHEMA BRONZE;

