-- Create RAW_EVENTS table:  

CREATE OR REPLACE TABLE SOCIAL_MEDIA_DB_AMS.BRONZE.RAW_EVENTS (
    EVENT_ID STRING,
    EVENT_TYPE STRING,

    USER_ID STRING,
    USERNAME STRING,
    COUNTRY STRING,
    USER_CREATED_AT TIMESTAMP_TZ,

    TARGET_USER_ID STRING,
    TARGET_USERNAME STRING,

    POST_ID STRING,
    POST_CREATOR_USER_ID STRING,
    POST_CREATED_AT TIMESTAMP_TZ,
    HASHTAG STRING,

    COMMENT_TEXT STRING,

    EVENT_TIMESTAMP TIMESTAMP_TZ,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);