-- Create USER_DIM table:

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.SILVER.USER_DIM (
    USER_ID STRING PRIMARY KEY,
    USERNAME STRING,
    COUNTRY STRING,
    CREATED_AT TIMESTAMP_TZ
);


-- Create POST_DIM table:

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.SILVER.POST_DIM (
    POST_ID STRING PRIMARY KEY,
    USER_ID STRING,
    HASHTAG STRING,
    CREATED_AT TIMESTAMP_TZ
);


--  Populate USER_DIM:   

INSERT INTO SOCIAL_MEDIA_DB_AMS.SILVER.USER_DIM
SELECT
    USER_ID,
    USERNAME,
    COUNTRY,
    USER_CREATED_AT AS CREATED_AT
FROM SOCIAL_MEDIA_DB_AMS.BRONZE.RAW_EVENTS
WHERE USER_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY USER_ID
    ORDER BY EVENT_TIMESTAMP
) = 1;


-- Populate POST_DIM

INSERT INTO SOCIAL_MEDIA_DB_AMS.SILVER.POST_DIM
SELECT
    POST_ID,
    POST_CREATOR_USER_ID AS USER_ID,
    HASHTAG,
    POST_CREATED_AT AS CREATED_AT
FROM SOCIAL_MEDIA_DB_AMS.BRONZE.RAW_EVENTS
WHERE POST_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY POST_ID
    ORDER BY EVENT_TIMESTAMP
) = 1;


