-- Create table CURATED_EVENTS:

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.SILVER.CURATED_EVENTS (
    EVENT_ID STRING PRIMARY KEY,
    EVENT_TYPE STRING,

    USER_ID STRING,
    USERNAME STRING,
    COUNTRY STRING,

    TARGET_USER_ID STRING,
    TARGET_USERNAME STRING,

    POST_ID STRING,
    POST_CREATOR_USER_ID STRING,
    HASHTAG STRING,

    COMMENT_TEXT STRING,

    EVENT_TIMESTAMP TIMESTAMP_TZ
);


-- Populate CURATED_EVENTS:

INSERT INTO SOCIAL_MEDIA_DB_AMS.SILVER.CURATED_EVENTS
SELECT
    r.EVENT_ID,
    r.EVENT_TYPE,

    r.USER_ID,
    u.USERNAME,
    u.COUNTRY,

    r.TARGET_USER_ID,
    tu.USERNAME AS TARGET_USERNAME,

    r.POST_ID,
    p.USER_ID AS POST_CREATOR_USER_ID,
    p.HASHTAG,

    r.COMMENT_TEXT,

    r.EVENT_TIMESTAMP

FROM SOCIAL_MEDIA_DB_AMS.BRONZE.RAW_EVENTS r

LEFT JOIN SOCIAL_MEDIA_DB_AMS.SILVER.USER_DIM u
    ON r.USER_ID = u.USER_ID

LEFT JOIN SOCIAL_MEDIA_DB_AMS.SILVER.USER_DIM tu
    ON r.TARGET_USER_ID = tu.USER_ID

LEFT JOIN SOCIAL_MEDIA_DB_AMS.SILVER.POST_DIM p
    ON r.POST_ID = p.POST_ID;