-- Create table INFLUENCER_RANKING:

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.GOLD.INFLUENCER_RANKING (
    USER_ID STRING,
    USERNAME STRING,
    LIKE_COUNT INTEGER,
    COMMENT_COUNT INTEGER,
    SHARE_COUNT INTEGER,
    TOTAL_ENGAGEMENT INTEGER,
    ENGAGEMENT_SCORE NUMBER(10,2),
    RANK INTEGER,
    CALCULATED_AT TIMESTAMP_TZ
);


-- Populate INFLUENCER_RANKING:

INSERT INTO SOCIAL_MEDIA_DB_AMS.GOLD.INFLUENCER_RANKING
(
    USER_ID,
    USERNAME,
    LIKE_COUNT,
    COMMENT_COUNT,
    SHARE_COUNT,
    TOTAL_ENGAGEMENT,
    ENGAGEMENT_SCORE,
    RANK,
    CALCULATED_AT
)
WITH engagement AS (
    SELECT
        POST_CREATOR_USER_ID AS USER_ID,
        SUM(CASE WHEN EVENT_TYPE = 'like' THEN 1 ELSE 0 END) AS LIKE_COUNT,
        SUM(CASE WHEN EVENT_TYPE = 'comment' THEN 1 ELSE 0 END) AS COMMENT_COUNT,
        SUM(CASE WHEN EVENT_TYPE = 'share' THEN 1 ELSE 0 END) AS SHARE_COUNT
    FROM SOCIAL_MEDIA_DB_AMS.SILVER.CURATED_EVENTS
    WHERE POST_CREATOR_USER_ID IS NOT NULL
      AND EVENT_TYPE IN ('like', 'comment', 'share')
    GROUP BY POST_CREATOR_USER_ID
),
scored AS (
    SELECT
        USER_ID,
        LIKE_COUNT,
        COMMENT_COUNT,
        SHARE_COUNT,
        LIKE_COUNT + COMMENT_COUNT + SHARE_COUNT AS TOTAL_ENGAGEMENT,
        LIKE_COUNT
            + (COMMENT_COUNT * 2)
            + (SHARE_COUNT * 3) AS ENGAGEMENT_SCORE
    FROM engagement
)
SELECT
    s.USER_ID,
    u.USERNAME,
    s.LIKE_COUNT,
    s.COMMENT_COUNT,
    s.SHARE_COUNT,
    s.TOTAL_ENGAGEMENT,
    s.ENGAGEMENT_SCORE,
    ROW_NUMBER() OVER (
        ORDER BY s.ENGAGEMENT_SCORE DESC
    ) AS RANK,
    CURRENT_TIMESTAMP() AS CALCULATED_AT
FROM scored s
LEFT JOIN SOCIAL_MEDIA_DB_AMS.SILVER.USER_DIM u
    ON s.USER_ID = u.USER_ID;