--- Real-time social media analytics platform

-- 1 Design RAW, CURATED and ANALYTICS layers in Snowflake (STEP 1)

-- Create SOCIAL_MEDIA_DB
        
CREATE OR REPLACE DATABASE SOCIAL_MEDIA_DB_AMS;

CREATE OR REPLACE SCHEMA SOCIAL_MEDIA_DB_AMS.RAW;
CREATE OR REPLACE SCHEMA SOCIAL_MEDIA_DB_AMS.CURATED;
CREATE OR REPLACE SCHEMA SOCIAL_MEDIA_DB_AMS.ANALYTICS;

USE WAREHOUSE LAB_WH_AMS;
USE DATABASE SOCIAL_MEDIA_DB_AMS;
USE SCHEMA RAW;




-- 2  – Snowflake RAW Layer (Step 5)
-- Create RAW_EVENTS table.

USE DATABASE SOCIAL_MEDIA_DB_AMS;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_EVENTS (
    EVENT_ID STRING,
    EVENT_TYPE STRING,
    USER_ID STRING,
    TARGET_USER_ID STRING,
    POST_ID STRING,
    HASHTAG STRING,
    COMMENT_TEXT STRING,
    EVENT_TIMESTAMP TIMESTAMP_TZ,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- verification

USE DATABASE SOCIAL_MEDIA_DB_AMS;
USE SCHEMA RAW;

SHOW TABLES;

-- remove tables 

DROP TABLE IF EXISTS SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS;

-- verify 

USE DATABASE SOCIAL_MEDIA_DB_AMS;
USE SCHEMA RAW;

SHOW TABLES;

--- Load streaming data into Snowflake.

--- check table 

SELECT COUNT(*) AS TOTAL_RAW_EVENTS
FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS;


-----check

SELECT *
FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS
ORDER BY INGESTED_AT DESC
LIMIT 10;

SELECT EVENT_ID, COUNT(*) AS CNT
FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS
GROUP BY EVENT_ID
HAVING COUNT(*) > 1;

-- add the primary key:

ALTER TABLE SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS
ADD CONSTRAINT PK_RAW_EVENTS
PRIMARY KEY (EVENT_ID);

----- verify 

SHOW PRIMARY KEYS IN TABLE SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS;

---

CREATE OR REPLACE TABLE SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS (
    EVENT_ID STRING,
    EVENT_TYPE STRING,

    USER_ID STRING,
    USERNAME STRING,
    COUNTRY STRING,
    USER_CREATED_AT TIMESTAMP_TZ,

    TARGET_USER_ID STRING,
    TARGET_USERNAME STRING,

    POST_ID STRING,
    POST_CREATOR_USER_ID STRING,
    POST_CREATED_AT TIMESTAMP_TZ,
    HASHTAG STRING,

    COMMENT_TEXT STRING,

    EVENT_TIMESTAMP TIMESTAMP_TZ,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

---  check table 

USE DATABASE SOCIAL_MEDIA_DB_AMS;
USE SCHEMA RAW;

SHOW TABLES


--- check invalid events 

SELECT EVENT_ID
FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS
WHERE EVENT_ID IN (
    'invalid_001',
    'invalid_002',
    'invalid_003',
    'invalid_004',
    'invalid_005',
    'invalid_006',
    'malformed_001'
);

-- streaming rate 

SELECT
    COUNT(*) AS TOTAL_EVENTS,
    MIN(EVENT_TIMESTAMP) AS FIRST_EVENT,
    MAX(EVENT_TIMESTAMP) AS LAST_EVENT
FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS;


-- Create USER_DIM with its PK

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM (
    USER_ID STRING PRIMARY KEY,
    USERNAME STRING,
    COUNTRY STRING,
    CREATED_AT TIMESTAMP_TZ
);


---  USER_DIM  populated

INSERT INTO SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM
SELECT
    USER_ID,
    USERNAME,
    COUNTRY,
    USER_CREATED_AT AS CREATED_AT
FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS
WHERE USER_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY USER_ID
    ORDER BY EVENT_TIMESTAMP
) = 1;

------ check 

SELECT COUNT(*) AS USER_COUNT
FROM SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM;

---- check actual rows 

SELECT *
FROM SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM
ORDER BY USER_ID
LIMIT 10;


----- POST_DIM

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.CURATED.POST_DIM (
    POST_ID STRING PRIMARY KEY,
    USER_ID STRING,
    HASHTAG STRING,
    CREATED_AT TIMESTAMP_TZ
);

--- populate it from RAW_EVENTS

INSERT INTO SOCIAL_MEDIA_DB_AMS.CURATED.POST_DIM
SELECT
    POST_ID,
    POST_CREATOR_USER_ID AS USER_ID,
    HASHTAG,
    POST_CREATED_AT AS CREATED_AT
FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS
WHERE POST_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY POST_ID
    ORDER BY EVENT_TIMESTAMP
) = 1;


-- check count SELECT COUNT(*) AS POST_COUNT

SELECT COUNT(*) AS POST_COUNT
FROM SOCIAL_MEDIA_DB_AMS.CURATED.POST_DIM;

--- overview 
SELECT *
FROM SOCIAL_MEDIA_DB_AMS.CURATED.POST_DIM
ORDER BY POST_ID
LIMIT 10;

---- CURATED_EVENTS

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS (
    EVENT_ID STRING PRIMARY KEY,
    EVENT_TYPE STRING,

    USER_ID STRING,
    USERNAME STRING,
    COUNTRY STRING,

    TARGET_USER_ID STRING,
    TARGET_USERNAME STRING,

    POST_ID STRING,
    POST_CREATOR_USER_ID STRING,
    HASHTAG STRING,

    COMMENT_TEXT STRING,

    EVENT_TIMESTAMP TIMESTAMP_TZ
);

--- populate it with the enrichment joins

INSERT INTO SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS
SELECT
    r.EVENT_ID,
    r.EVENT_TYPE,

    r.USER_ID,
    u.USERNAME,
    u.COUNTRY,

    r.TARGET_USER_ID,
    tu.USERNAME AS TARGET_USERNAME,

    r.POST_ID,
    p.USER_ID AS POST_CREATOR_USER_ID,
    p.HASHTAG,

    r.COMMENT_TEXT,

    r.EVENT_TIMESTAMP

FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS r

LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM u
    ON r.USER_ID = u.USER_ID

LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM tu
    ON r.TARGET_USER_ID = tu.USER_ID

LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.POST_DIM p
    ON r.POST_ID = p.POST_ID;

--- check count 

SELECT COUNT(*) AS CURATED_EVENT_COUNT
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS;


--- overview 

SELECT *
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS
ORDER BY EVENT_TIMESTAMP DESC
LIMIT 10;


-- step 7 Trending Hashtag Analytic

--- Create TRENDING_HASHTAGS

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.ANALYTICS.TRENDING_HASHTAGS (
    WINDOW_MINUTES INTEGER,
    HASHTAG STRING,
    EVENT_COUNT INTEGER,
    RANK INTEGER,
    WINDOW_START TIMESTAMP_TZ,
    WINDOW_END TIMESTAMP_TZ
);

-- check

SELECT *
FROM SOCIAL_MEDIA_DB_AMS.ANALYTICS.TRENDING_HASHTAGS

-- Calculate the 1-minute results

SELECT
    MIN(EVENT_TIMESTAMP) AS OLDEST_EVENT,
    MAX(EVENT_TIMESTAMP) AS NEWEST_EVENT,
    CURRENT_TIMESTAMP() AS CURRENT_TIME
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS;

SELECT
    HASHTAG,
    COUNT(*) AS EVENT_COUNT
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS
WHERE HASHTAG IS NOT NULL
  AND EVENT_TIMESTAMP >= DATEADD(MINUTE, -1, CURRENT_TIMESTAMP())
GROUP BY HASHTAG
ORDER BY EVENT_COUNT DESC;

-- 
SELECT
    COUNT(*) AS RAW_COUNT,
    COUNT(DISTINCT EVENT_ID) AS RAW_UNIQUE_EVENTS
FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS;

SELECT
    COUNT(*) AS CURATED_COUNT,
    COUNT(DISTINCT EVENT_ID) AS CURATED_UNIQUE_EVENTS
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS;


--- check table 

SELECT COUNT(*) AS TOTAL_RAW_EVENTS
FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS;



-- merge query

MERGE INTO SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS AS target
USING (
    SELECT
        r.EVENT_ID,
        r.EVENT_TYPE,
        r.USER_ID,
        u.USERNAME,
        u.COUNTRY,
        r.TARGET_USER_ID,
        tu.USERNAME AS TARGET_USERNAME,
        r.POST_ID,
        p.USER_ID AS POST_CREATOR_USER_ID,
        p.HASHTAG,
        r.COMMENT_TEXT,
        r.EVENT_TIMESTAMP
    FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS r

    LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM u
        ON r.USER_ID = u.USER_ID

    LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM tu
        ON r.TARGET_USER_ID = tu.USER_ID

    LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.POST_DIM p
        ON r.POST_ID = p.POST_ID

    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY r.EVENT_ID
        ORDER BY r.EVENT_TIMESTAMP DESC
    ) = 1
) AS source

ON target.EVENT_ID = source.EVENT_ID

WHEN NOT MATCHED THEN
    INSERT (
        EVENT_ID,
        EVENT_TYPE,
        USER_ID,
        USERNAME,
        COUNTRY,
        TARGET_USER_ID,
        TARGET_USERNAME,
        POST_ID,
        POST_CREATOR_USER_ID,
        HASHTAG,
        COMMENT_TEXT,
        EVENT_TIMESTAMP
    )

    VALUES (
        source.EVENT_ID,
        source.EVENT_TYPE,
        source.USER_ID,
        source.USERNAME,
        source.COUNTRY,
        source.TARGET_USER_ID,
        source.TARGET_USERNAME,
        source.POST_ID,
        source.POST_CREATOR_USER_ID,
        source.HASHTAG,
        source.COMMENT_TEXT,
        source.EVENT_TIMESTAMP
    );



    SELECT
    COUNT(*) AS CURATED_COUNT,
    COUNT(DISTINCT EVENT_ID) AS CURATED_UNIQUE_EVENTS,
    MAX(EVENT_TIMESTAMP) AS LATEST_EVENT
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS;

--- trendign hashtags 

INSERT INTO SOCIAL_MEDIA_DB_AMS.ANALYTICS.TRENDING_HASHTAGS
(
    WINDOW_MINUTES,
    HASHTAG,
    EVENT_COUNT,
    RANK,
    WINDOW_START,
    WINDOW_END
)

WITH windows AS (
    SELECT 1 AS WINDOW_MINUTES
    UNION ALL
    SELECT 5
    UNION ALL
    SELECT 15
),

counts AS (
    SELECT
        w.WINDOW_MINUTES,
        c.HASHTAG,
        COUNT(*) AS EVENT_COUNT,

        DATEADD(
            MINUTE,
            -w.WINDOW_MINUTES,
            CURRENT_TIMESTAMP()
        ) AS WINDOW_START,

        CURRENT_TIMESTAMP() AS WINDOW_END

    FROM windows w

    JOIN SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS c
        ON c.HASHTAG IS NOT NULL
        AND c.EVENT_TIMESTAMP >= DATEADD(
            MINUTE,
            -w.WINDOW_MINUTES,
            CURRENT_TIMESTAMP()
        )

    GROUP BY
        w.WINDOW_MINUTES,
        c.HASHTAG
),

ranked AS (
    SELECT
        WINDOW_MINUTES,
        HASHTAG,
        EVENT_COUNT,

        ROW_NUMBER() OVER (
            PARTITION BY WINDOW_MINUTES
            ORDER BY EVENT_COUNT DESC
        ) AS RANK,

        WINDOW_START,
        WINDOW_END

    FROM counts
)

SELECT
    WINDOW_MINUTES,
    HASHTAG,
    EVENT_COUNT,
    RANK,
    WINDOW_START,
    WINDOW_END

FROM ranked

WHERE RANK <= 10;


SELECT
    WINDOW_MINUTES,
    RANK,
    HASHTAG,
    EVENT_COUNT,
    WINDOW_START,
    WINDOW_END
FROM SOCIAL_MEDIA_DB_AMS.ANALYTICS.TRENDING_HASHTAGS
ORDER BY
    WINDOW_MINUTES,
    RANK;

-- check timing 

SELECT
    MAX(EVENT_TIMESTAMP) AS LATEST_EVENT,
    CURRENT_TIMESTAMP() AS NOW,
    DATEDIFF(
        SECOND,
        MAX(EVENT_TIMESTAMP),
        CURRENT_TIMESTAMP()
    ) AS SECONDS_BEHIND
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS;


---- update CURATED


MERGE INTO SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS AS target
USING (
    SELECT
        r.EVENT_ID,
        r.EVENT_TYPE,
        r.USER_ID,
        u.USERNAME,
        u.COUNTRY,
        r.TARGET_USER_ID,
        tu.USERNAME AS TARGET_USERNAME,
        r.POST_ID,
        p.USER_ID AS POST_CREATOR_USER_ID,
        p.HASHTAG,
        r.COMMENT_TEXT,
        r.EVENT_TIMESTAMP
    FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS r
    LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM u
        ON r.USER_ID = u.USER_ID
    LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM tu
        ON r.TARGET_USER_ID = tu.USER_ID
    LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.POST_DIM p
        ON r.POST_ID = p.POST_ID
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY r.EVENT_ID
        ORDER BY r.EVENT_TIMESTAMP DESC
    ) = 1
) AS source
ON target.EVENT_ID = source.EVENT_ID

WHEN NOT MATCHED THEN
INSERT (
    EVENT_ID,
    EVENT_TYPE,
    USER_ID,
    USERNAME,
    COUNTRY,
    TARGET_USER_ID,
    TARGET_USERNAME,
    POST_ID,
    POST_CREATOR_USER_ID,
    HASHTAG,
    COMMENT_TEXT,
    EVENT_TIMESTAMP
)
VALUES (
    source.EVENT_ID,
    source.EVENT_TYPE,
    source.USER_ID,
    source.USERNAME,
    source.COUNTRY,
    source.TARGET_USER_ID,
    source.TARGET_USERNAME,
    source.POST_ID,
    source.POST_CREATOR_USER_ID,
    source.HASHTAG,
    source.COMMENT_TEXT,
    source.EVENT_TIMESTAMP
);


----- verify curated 

SELECT
    COUNT(*) AS CURATED_COUNT,
    MAX(EVENT_TIMESTAMP) AS LATEST_EVENT
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS;

--- Calculate the 1-minute hashtags

SELECT
    HASHTAG,
    COUNT(*) AS EVENT_COUNT
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS
WHERE HASHTAG IS NOT NULL
  AND EVENT_TIMESTAMP >= DATEADD(MINUTE, -1, CURRENT_TIMESTAMP())
GROUP BY HASHTAG
ORDER BY EVENT_COUNT DESC;


--- table for step 7

INSERT INTO SOCIAL_MEDIA_DB_AMS.ANALYTICS.TRENDING_HASHTAGS
(
    WINDOW_MINUTES,
    HASHTAG,
    EVENT_COUNT,
    RANK,
    WINDOW_START,
    WINDOW_END
)
WITH ranked AS (
    SELECT
        HASHTAG,
        COUNT(*) AS EVENT_COUNT,
        ROW_NUMBER() OVER (
            ORDER BY COUNT(*) DESC
        ) AS RANK
    FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS
    WHERE HASHTAG IS NOT NULL
      AND EVENT_TIMESTAMP >= DATEADD(
          MINUTE,
          -1,
          CURRENT_TIMESTAMP()
      )
    GROUP BY HASHTAG
)
SELECT
    1 AS WINDOW_MINUTES,
    HASHTAG,
    EVENT_COUNT,
    RANK,
    DATEADD(MINUTE, -1, CURRENT_TIMESTAMP()) AS WINDOW_START,
    CURRENT_TIMESTAMP() AS WINDOW_END
FROM ranked
WHERE RANK <= 10;

---- verify Step 7

SELECT
    WINDOW_MINUTES,
    RANK,
    HASHTAG,
    EVENT_COUNT,
    WINDOW_START,
    WINDOW_END
FROM SOCIAL_MEDIA_DB_AMS.ANALYTICS.TRENDING_HASHTAGS
ORDER BY
    WINDOW_MINUTES,
    RANK;



--- incremental merge 

MERGE INTO SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS AS target
USING (
    SELECT
        r.EVENT_ID,
        r.EVENT_TYPE,
        r.USER_ID,
        u.USERNAME,
        u.COUNTRY,
        r.TARGET_USER_ID,
        tu.USERNAME AS TARGET_USERNAME,
        r.POST_ID,
        p.USER_ID AS POST_CREATOR_USER_ID,
        p.HASHTAG,
        r.COMMENT_TEXT,
        r.EVENT_TIMESTAMP
    FROM SOCIAL_MEDIA_DB_AMS.RAW.RAW_EVENTS r
    LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM u
        ON r.USER_ID = u.USER_ID
    LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM tu
        ON r.TARGET_USER_ID = tu.USER_ID
    LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.POST_DIM p
        ON r.POST_ID = p.POST_ID
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY r.EVENT_ID
        ORDER BY r.EVENT_TIMESTAMP DESC
    ) = 1
) AS source
ON target.EVENT_ID = source.EVENT_ID

WHEN NOT MATCHED THEN
INSERT (
    EVENT_ID,
    EVENT_TYPE,
    USER_ID,
    USERNAME,
    COUNTRY,
    TARGET_USER_ID,
    TARGET_USERNAME,
    POST_ID,
    POST_CREATOR_USER_ID,
    HASHTAG,
    COMMENT_TEXT,
    EVENT_TIMESTAMP
)
VALUES (
    source.EVENT_ID,
    source.EVENT_TYPE,
    source.USER_ID,
    source.USERNAME,
    source.COUNTRY,
    source.TARGET_USER_ID,
    source.TARGET_USERNAME,
    source.POST_ID,
    source.POST_CREATOR_USER_ID,
    source.HASHTAG,
    source.COMMENT_TEXT,
    source.EVENT_TIMESTAMP
);

--- Check for viral posts



SELECT
    POST_ID,
    COUNT(*) AS LIKE_COUNT
FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS
WHERE EVENT_TYPE = 'like'
  AND POST_ID IS NOT NULL
  AND EVENT_TIMESTAMP >= DATEADD(
      MINUTE,
      -5,
      CURRENT_TIMESTAMP()
  )
GROUP BY POST_ID
HAVING COUNT(*) > 500
ORDER BY LIKE_COUNT DESC;



-- Create VIRAL_POSTS

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.ANALYTICS.VIRAL_POSTS (
    POST_ID STRING,
    LIKE_COUNT INTEGER,
    WINDOW_MINUTES INTEGER,
    WINDOW_START TIMESTAMP_TZ,
    WINDOW_END TIMESTAMP_TZ,
    VIRAL_DETECTED_AT TIMESTAMP_TZ
);

--- populate viral posts 

INSERT INTO SOCIAL_MEDIA_DB_AMS.ANALYTICS.VIRAL_POSTS
(
    POST_ID,
    LIKE_COUNT,
    WINDOW_MINUTES,
    WINDOW_START,
    WINDOW_END,
    VIRAL_DETECTED_AT
)
WITH viral AS (
    SELECT
        POST_ID,
        COUNT(*) AS LIKE_COUNT
    FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS
    WHERE EVENT_TYPE = 'like'
      AND POST_ID IS NOT NULL
      AND EVENT_TIMESTAMP >= DATEADD(
          MINUTE,
          -5,
          CURRENT_TIMESTAMP()
      )
    GROUP BY POST_ID
    HAVING COUNT(*) > 500
)
SELECT
    POST_ID,
    LIKE_COUNT,
    5 AS WINDOW_MINUTES,
    DATEADD(MINUTE, -5, CURRENT_TIMESTAMP()) AS WINDOW_START,
    CURRENT_TIMESTAMP() AS WINDOW_END,
    CURRENT_TIMESTAMP() AS VIRAL_DETECTED_AT
FROM viral;


-- check table 

SELECT *
FROM SOCIAL_MEDIA_DB_AMS.ANALYTICS.VIRAL_POSTS
ORDER BY VIRAL_DETECTED_AT DESC;


-- Create INFLUENCER_RANKING

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.ANALYTICS.INFLUENCER_RANKING (
    USER_ID STRING,
    USERNAME STRING,
    LIKE_COUNT INTEGER,
    COMMENT_COUNT INTEGER,
    SHARE_COUNT INTEGER,
    TOTAL_ENGAGEMENT INTEGER,
    ENGAGEMENT_SCORE NUMBER(10,2),
    RANK INTEGER,
    CALCULATED_AT TIMESTAMP_TZ
);

--- We'll count likes, comments, and shares by the post creator, then calculate:
-- Engagement Score = Likes + (Comments × 2) + (Shares × 3)

INSERT INTO SOCIAL_MEDIA_DB_AMS.ANALYTICS.INFLUENCER_RANKING
(
    USER_ID,
    USERNAME,
    LIKE_COUNT,
    COMMENT_COUNT,
    SHARE_COUNT,
    TOTAL_ENGAGEMENT,
    ENGAGEMENT_SCORE,
    RANK,
    CALCULATED_AT
)
WITH engagement AS (
    SELECT
        POST_CREATOR_USER_ID AS USER_ID,
        SUM(CASE WHEN EVENT_TYPE = 'like' THEN 1 ELSE 0 END) AS LIKE_COUNT,
        SUM(CASE WHEN EVENT_TYPE = 'comment' THEN 1 ELSE 0 END) AS COMMENT_COUNT,
        SUM(CASE WHEN EVENT_TYPE = 'share' THEN 1 ELSE 0 END) AS SHARE_COUNT
    FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS
    WHERE POST_CREATOR_USER_ID IS NOT NULL
      AND EVENT_TYPE IN ('like', 'comment', 'share')
    GROUP BY POST_CREATOR_USER_ID
),
scored AS (
    SELECT
        USER_ID,
        LIKE_COUNT,
        COMMENT_COUNT,
        SHARE_COUNT,
        LIKE_COUNT + COMMENT_COUNT + SHARE_COUNT AS TOTAL_ENGAGEMENT,
        LIKE_COUNT
            + (COMMENT_COUNT * 2)
            + (SHARE_COUNT * 3) AS ENGAGEMENT_SCORE
    FROM engagement
)
SELECT
    s.USER_ID,
    u.USERNAME,
    s.LIKE_COUNT,
    s.COMMENT_COUNT,
    s.SHARE_COUNT,
    s.TOTAL_ENGAGEMENT,
    s.ENGAGEMENT_SCORE,
    ROW_NUMBER() OVER (
        ORDER BY s.ENGAGEMENT_SCORE DESC
    ) AS RANK,
    CURRENT_TIMESTAMP() AS CALCULATED_AT
FROM scored s
LEFT JOIN SOCIAL_MEDIA_DB_AMS.CURATED.USER_DIM u
    ON s.USER_ID = u.USER_ID;

    --- check 

SELECT *
FROM SOCIAL_MEDIA_DB_AMS.ANALYTICS.INFLUENCER_RANKING
ORDER BY RANK
LIMIT 10;

--- Create COMMENT_SENTIMENT

CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA_DB_AMS.ANALYTICS.COMMENT_SENTIMENT (
    EVENT_ID STRING,
    POST_ID STRING,
    USER_ID STRING,
    COMMENT_TEXT STRING,
    SENTIMENT STRING,
    EVENT_TIMESTAMP TIMESTAMP_TZ,
    CALCULATED_AT TIMESTAMP_TZ
);

--- populate sentiment 

INSERT INTO SOCIAL_MEDIA_DB_AMS.ANALYTICS.COMMENT_SENTIMENT
(
    EVENT_ID,
    POST_ID,
    USER_ID,
    COMMENT_TEXT,
    SENTIMENT,
    EVENT_TIMESTAMP,
    CALCULATED_AT
)
SELECT
    EVENT_ID,
    POST_ID,
    USER_ID,
    COMMENT_TEXT,

    CASE
        WHEN LOWER(COMMENT_TEXT) IN (
            'amazing!',
            'love this!',
            'this is fantastic!',
            'great post!',
            'absolutely beautiful!',
            'this made my day!',
            'so inspiring!',
            'i really enjoyed this!',
            'wonderful content!',
            'this is awesome!',
            'great job!',
            'i love it!',
            'very helpful!',
            'fantastic video!',
            'such a great experience!'
        )
        THEN 'Positive'

        WHEN LOWER(COMMENT_TEXT) IN (
            'interesting.',
            'thanks for sharing.',
            'i see.',
            'good to know.',
            'interesting information.',
            'thanks for posting.',
            'i had not seen this before.',
            'this is useful information.',
            'nice post.',
            'good information.',
            'i will keep this in mind.',
            'interesting perspective.',
            'thanks for the update.',
            'i understand.',
            'noted.'
        )
        THEN 'Neutral'

        WHEN LOWER(COMMENT_TEXT) IN (
            'i don''t like this.',
            'this was disappointing.',
            'not very useful.',
            'i disagree with this.',
            'this could be much better.',
            'i did not enjoy this.',
            'this is disappointing.',
            'the quality is poor.',
            'i expected more.',
            'not a good experience.',
            'this did not work for me.',
            'i am not impressed.',
            'unfortunately this was bad.',
            'i don''t recommend this.',
            'this needs improvement.'
        )
        THEN 'Negative'

        ELSE 'Neutral'
    END AS SENTIMENT,

    EVENT_TIMESTAMP,
    CURRENT_TIMESTAMP() AS CALCULATED_AT

FROM SOCIAL_MEDIA_DB_AMS.CURATED.CURATED_EVENTS
WHERE EVENT_TYPE = 'comment'
  AND COMMENT_TEXT IS NOT NULL;


-- verify
SELECT
    SENTIMENT,
    COUNT(*) AS COMMENT_COUNT
FROM SOCIAL_MEDIA_DB_AMS.ANALYTICS.COMMENT_SENTIMENT
GROUP BY SENTIMENT
ORDER BY COMMENT_COUNT DESC;

-- sentiment overtime 

SELECT
    DATE_TRUNC('HOUR', EVENT_TIMESTAMP) AS HOUR,
    SENTIMENT,
    COUNT(*) AS COMMENT_COUNT
FROM SOCIAL_MEDIA_DB_AMS.ANALYTICS.COMMENT_SENTIMENT
GROUP BY
    DATE_TRUNC('HOUR', EVENT_TIMESTAMP),
    SENTIMENT
ORDER BY
    HOUR,
    SENTIMENT;

---
