CREATE OR REPLACE DATABASE SOCIAL_MEDIA_DB_AMS;

CREATE OR REPLACE SCHEMA SOCIAL_MEDIA_DB_AMS.RAW;
CREATE OR REPLACE SCHEMA SOCIAL_MEDIA_DB_AMS.CURATED;
CREATE OR REPLACE SCHEMA SOCIAL_MEDIA_DB_AMS.ANALYTICS;

USE WAREHOUSE LAB_WH_AMS;
USE DATABASE SOCIAL_MEDIA_DB_AMS;
USE SCHEMA RAW;